name: citibike-dc
channels:
  - python
  - pyviz
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - datashader
  - pandas
  - numpy
  - hvplot
  - holoviews
  - xyzservice
packages:
- jupyter-panel-proxy

